version = 0.1

[default.deploy.parameters]
stack_name = "data-pipeline-stack"
resolve_s3 = true
s3_prefix = "data-pipeline-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
